name: "SBOM-TM CI Security Gate"
description: "Commit-aware SBOM + Trivy + RuleEngine diff/scan for PRs and pushes"
author: "Hitesh / sbom-tm"

branding:
  icon: "shield"
  color: "purple"

inputs:
  mode:
    description: "auto | scan | diff"
    required: false
    default: "auto"

  base:
    description: "Base ref for diff"
    required: false
    default: ""

  project:
    description: "Project name for reports"
    required: false
    default: "default"

  offline:
    description: "Use Trivy offline mode"
    required: false
    default: "false"

  report-path:
    description: "Path for Markdown report"
    required: false
    default: "sbom-tm-report.md"

outputs:
  report_path:
    description: "Markdown report path"

runs:
  using: "docker"
  image: "ghcr.io/h-strangeone/sbom-tm:latest"
