name: "SBOM-TM CI Security Gate"
description: "Commit-aware SBOM + Trivy + RuleEngine diff/scan inside GitHub Actions"
author: "Hitesh / sbom-tm"

branding:
  icon: "shield"
  color: "purple"

inputs:
  mode:
    description: "auto | scan | diff"
    required: false
    default: "auto"

  base:
    description: "Base ref for diff"
    required: false
    default: ""

  project:
    description: "Project name (used in reports)"
    required: false
    default: "default"

  offline:
    description: "Use Trivy offline mode (true/false)"
    required: false
    default: "false"

  report-path:
    description: "Markdown report output path"
    required: false
    default: "sbom-tm-report.md"

outputs:
  report_path:
    description: "Location of markdown diff report"

runs:
  using: "docker"
  image: "ghcr.io/h-strangeone/sbom-tm:latest"

  args:
    - ${{ inputs.mode }}
    - ${{ inputs.base }}
    - ${{ inputs.project }}
    - ${{ inputs.offline }}
    - ${{ inputs['report-path'] }}


